services:
  neo4j:
    image: neo4j:5.26-enterprise
    container_name: neo4j-tdg
    ports:
      - 7474:7474
      - 7687:7687
      - 2004:2004
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      # Uncomment the following line during Chapter 2
      #NEO4J_server_memory_heap_max__size: "128M"
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_server_metrics_prometheus_enabled: true
      NEO4J_server_metrics_prometheus_endpoint: "0.0.0.0:2004"
      NEO4J_server_metrics_csv_enabled: false
      NEO4J_server_metrics_filter: '*'
    volumes:
      - "./import:/import"
      - "./data:/data"
      # Uncomment the following during Chapter 11
      # - "./conf/server-logs.xml:/var/lib/neo4j/conf/server-logs.xml"